"""Kernel symbol policy for Matrix."""

from .boolean_functions import (
    FUNCTIONS_BY_ID,
    FUNCTIONS_BY_NAME,
    ROW_ORDER,
    BinaryBooleanFunction,
    get_boolean_function,
)
from .bitwise_execution import (
    bit_not,
    build_truth_table_masks,
    constant_mask,
    evaluate_formula_mask,
    mask_popcount,
    mask_reduce_and,
    mask_reduce_or,
    normalize_mask_family,
)
from .boolean_algebra import canonicalize_formula, clause_subsumes, dual_formula, reduce_cnf_subsumption, reduce_dnf_subsumption
from .formulas import (
    AndFormula,
    ConstantFormula,
    Formula,
    IfFormula,
    KernelAtom,
    NotFormula,
    OrFormula,
    RelationAtom,
    formula_precedence,
    parse_formula,
)
from .formula_evaluation import (
    FormulaClassification,
    classify_formula,
    collect_atoms,
    evaluate_formula,
    iter_valuations,
)
from .formula_inference import conjunction_elimination, disjunctive_syllogism, hypothetical_syllogism, modus_ponens
from .formula_normal_forms import to_cnf, to_dnf, to_nnf
from .formula_rewrites import desugar_if, simplify_formula, sort_formula_operands
from .symbol_policy import (
    KERNEL_CONNECTIVES,
    KERNEL_META_RELATIONS,
    WI_RELATION_FAMILIES,
    SymbolPolicy,
    classify_symbol,
    is_kernel_symbol,
)

__all__ = [
    "AndFormula",
    "BinaryBooleanFunction",
    "bit_not",
    "build_truth_table_masks",
    "canonicalize_formula",
    "clause_subsumes",
    "ConstantFormula",
    "FUNCTIONS_BY_ID",
    "FUNCTIONS_BY_NAME",
    "Formula",
    "FormulaClassification",
    "IfFormula",
    "KERNEL_CONNECTIVES",
    "KERNEL_META_RELATIONS",
    "KernelAtom",
    "NotFormula",
    "OrFormula",
    "RelationAtom",
    "ROW_ORDER",
    "WI_RELATION_FAMILIES",
    "classify_formula",
    "collect_atoms",
    "conjunction_elimination",
    "constant_mask",
    "desugar_if",
    "disjunctive_syllogism",
    "dual_formula",
    "evaluate_formula",
    "evaluate_formula_mask",
    "formula_precedence",
    "hypothetical_syllogism",
    "iter_valuations",
    "mask_popcount",
    "mask_reduce_and",
    "mask_reduce_or",
    "modus_ponens",
    "get_boolean_function",
    "normalize_mask_family",
    "parse_formula",
    "reduce_cnf_subsumption",
    "reduce_dnf_subsumption",
    "simplify_formula",
    "sort_formula_operands",
    "SymbolPolicy",
    "to_cnf",
    "to_dnf",
    "to_nnf",
    "classify_symbol",
    "is_kernel_symbol",
]
